use_frameworks!

target 'dotLottieLoader_Example' do
  platform :ios, '11.0'
  pod 'dotLottieLoader', :path => '../'

  target 'dotLottieLoader_Tests' do
    inherit! :search_paths

    
  end
end

target 'dotLottieLoader_watchos Extension' do
  platform :watchos, '6.0'
  pod 'dotLottieLoader', :path => '../'
end
