use_frameworks!

target 'dotLottieLoader_Example' do
  pod 'dotLottieLoader', :path => '../'

  target 'dotLottieLoader_Tests' do
    inherit! :search_paths

    
  end
end

target 'dotLottieLoader_watchos Extension' do
  pod 'dotLottieLoader', :path => '../'
end
